'use client';
import Link from 'next/link';
import { ArrowLeft, FileText, Layers, Check, ArrowUpRight } from 'lucide-react';
import { Brand } from './brand';
import { LanguageSwitch, useLanguage } from './language';

export function AccountShell({ children }: { children: React.ReactNode }) {
  const { locale } = useLanguage();
  const en = locale === 'en';
  return <main className="account-page"><div className="account-layout"><section className="account-content"><header className="account-nav"><Link href="/" aria-label={en ? 'Back to Precidoc' : 'Kembali ke Precidoc'}><ArrowLeft size={18}/><Brand/></Link><LanguageSwitch/></header><div className="account-form-panel">{children}</div><footer className="account-footer">© {new Date().getFullYear()} Rainc <Link href="/sample">{en ? 'Explore the sample' : 'Jelajahi contoh'}<ArrowUpRight size={14}/></Link></footer></section><aside className="account-art"><div className="account-art-copy"><span>DOCUMENTS → KNOWLEDGE</span><h2>{en ? 'Better context.' : 'Konteks lebih baik.'}<br/>{en ? 'Clearer sources.' : 'Sumber lebih jelas.'}</h2><p>{en ? 'Prepare your documents before they become part of your AI knowledge base.' : 'Siapkan dokumen sebelum menjadi bagian dari knowledge base AI kamu.'}</p></div><div className="account-illustration" aria-hidden="true"><div className="art-document"><div className="art-card-label"><FileText size={18}/> RUNBOOK.md</div><h3>Database recovery</h3><div className="art-line wide"/><div className="art-line"/><div className="art-line short"/><div className="art-section">01 / Prerequisites</div><div className="art-line wide"/><div className="art-line"/><div className="art-section">02 / Recovery procedure</div><div className="art-line wide"/><div className="art-line short"/></div><div className="art-chunks"><div className="art-card-label"><Layers size={18}/>{en ? 'PREPARED CHUNKS' : 'CHUNK DIPERSIAPKAN'}</div>{['01', '02', '03'].map(n=><div className="art-chunk" key={n}><span>{n}</span><div><div className="art-line wide"/><div className="art-line short"/></div><Check size={16}/></div>)}<div className="art-source"><Check size={14}/>{en ? 'Source references preserved' : 'Referensi sumber tetap terhubung'}</div></div><div className="art-export">JSON <span>+</span> Markdown <ArrowUpRight size={16}/></div></div><div className="account-art-foot"><span>{en?'Upload':'Unggah'}</span><span>{en?'Analyze':'Analisis'}</span><span>{en?'Optimize':'Rapikan'}</span><span>Export</span></div></aside></div></main>;
}
