'use client';

import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, ArrowLeft } from 'lucide-react';
import { MarketingHeader, MarketingFooter } from '@/components/marketing-shell';
import { useLanguage } from '@/components/language';
import { posts, postTitle, readingMinutes, type BlogPost } from '@/lib/blog';

const categories = { en: { extract: 'PDF extraction', chunk: 'Chunking', export: 'Export' }, id: { extract: 'Ekstraksi PDF', chunk: 'Chunking', export: 'Export' } };
function PostMeta({ post }: { post: BlogPost }) {
  const { locale } = useLanguage();
  return <div className="post-meta"><span>{categories[locale][post.category]}</span><time dateTime={post.published}>{new Intl.DateTimeFormat(locale === 'en' ? 'en-GB' : 'id-ID', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(post.published + 'T12:00:00Z'))}</time><span>{readingMinutes(post, locale)} {locale === 'en' ? 'min read' : 'menit baca'}</span></div>;
}
function ArticleFigure({ category }: { category: BlogPost['category'] }) {
  const { locale } = useLanguage();
  return <div className={`article-figure figure-${category}`} aria-hidden="true"><span className="figure-label">{category === 'extract' ? 'PDF → TEXT' : category === 'chunk' ? 'RUNBOOK → CHUNKS' : 'DOCUMENT → EXPORT'}</span>{category === 'extract' ? <div className="figure-paper"><span>Database-Recovery.pdf</span><strong>{locale === 'en' ? 'Check the reading order.' : 'Periksa urutan baca.'}</strong><div className="figure-columns"><div><b>01</b><i /><i /><i /></div><div><b>02</b><i /><i /><i /></div></div><div className="figure-reference">page 01 · page 02 <ArrowRight size={16} /></div></div> : category === 'chunk' ? <div className="figure-chunks">{['Prerequisites', 'Recovery procedure', 'Verification'].map((label, index) => <div key={label}><span>0{index + 1}</span><strong>{locale === 'en' ? label : ['Prasyarat', 'Prosedur pemulihan', 'Verifikasi'][index]}</strong><small>section_0{index + 1}</small></div>)}</div> : <div className="figure-export"><span>reviewed-export.json</span><pre>{'{\n  "version": "1.0",\n  "reviewed": true,\n  "source": "section_03"\n}'}</pre><small>{locale === 'en' ? 'Illustrative fields' : 'Ilustrasi field'}</small></div>}</div>;
}
export function BlogIndex() {
  const { locale } = useLanguage();
  const [category, setCategory] = useState<'all' | BlogPost['category']>('all');
  const visible = posts.filter(post => category === 'all' || post.category === category);
  return <div className="landing saas-landing public-page"><MarketingHeader /><main className="container public-main journal-main"><header className="public-intro"><span className="public-eyebrow">PRECIDOC / BLOG</span><h1>{locale === 'en' ? 'From document' : 'Dari dokumen'}<br /><span>{locale === 'en' ? 'to knowledge base.' : 'ke knowledge base.'}</span></h1><p>{locale === 'en' ? 'Practical guides to checking extracted text, splitting runbooks, and keeping the sources close.' : 'Panduan praktis untuk memeriksa hasil ekstraksi, membagi runbook, dan menjaga referensi sumber.'}</p></header><div className="journal-filters" role="group" aria-label={locale === 'en' ? 'Filter articles by topic' : 'Filter artikel berdasarkan topik'}>{(['all', 'extract', 'chunk', 'export'] as const).map(value => <button key={value} type="button" aria-pressed={category === value} onClick={() => setCategory(value)}>{value === 'all' ? (locale === 'en' ? 'All guides' : 'Semua panduan') : categories[locale][value]}</button>)}</div><p className="journal-count" role="status">{visible.length} {locale === 'en' ? (visible.length === 1 ? 'guide' : 'guides') : 'panduan'}</p><div className="journal-articles">{visible.map((post, index) => <article key={post.slug} className={index === 0 ? 'journal-featured' : 'journal-row'}><div><PostMeta post={post} /><h2><Link href={`/blog/${post.slug}`}>{postTitle(post, locale)}</Link></h2><p>{post[locale].excerpt}</p><Link href={`/blog/${post.slug}`} className="public-text-link" aria-label={`${locale === 'en' ? 'Read' : 'Baca'}: ${postTitle(post, locale)}`}>{locale === 'en' ? 'Read the guide' : 'Baca panduan'}<ArrowRight size={16} aria-hidden="true" /></Link></div><ArticleFigure category={post.category} /></article>)}</div><div className="journal-bottom"><p>{locale === 'en' ? 'Put the guide into practice with the built-in runbook.' : 'Coba panduannya langsung dengan runbook contoh.'}</p><Link href="/sample" className="button primary">{locale === 'en' ? 'Open sample workspace' : 'Buka workspace contoh'}<ArrowRight size={16} aria-hidden="true" /></Link></div></main><MarketingFooter /></div>;
}
export function BlogArticle({ post }: { post: BlogPost }) {
  const { locale } = useLanguage();
  const copy = post[locale];
  return <div className="landing saas-landing public-page"><MarketingHeader /><main className="container public-main article-main"><Link href="/blog" className="public-text-link article-back"><ArrowLeft size={16} aria-hidden="true" />{locale === 'en' ? 'All guides' : 'Semua panduan'}</Link><article><header className="article-intro"><PostMeta post={post} /><h1>{postTitle(post, locale)}</h1><p>{copy.excerpt}</p><span className="article-byline">{locale === 'en' ? 'By Precidoc' : 'Oleh Precidoc'}</span></header><div className="article-layout"><aside className="article-toc"><nav aria-label={locale === 'en' ? 'On this page' : 'Di halaman ini'}><strong>{locale === 'en' ? 'On this page' : 'Di halaman ini'}</strong>{copy.sections.map(section => <a key={section.id} href={`#${section.id}`}>{section.heading}</a>)}</nav></aside><div className="article-body">{copy.sections.map(section => <section id={section.id} key={section.id}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}{section.list && <ul>{section.list.map(item => <li key={item}>{item}</li>)}</ul>}{section.example && <pre tabIndex={0}>{section.example}</pre>}</section>)}<div className="article-practice"><span className="public-eyebrow">{locale === 'en' ? 'TRY IT IN PRECIDOC' : 'COBA DI PRECIDOC'}</span><h2>{locale === 'en' ? 'Open the example and check it yourself.' : 'Buka contoh dan periksa sendiri.'}</h2><Link href={`/sample?tab=${post.sampleTab}`} className="button primary">{locale === 'en' ? 'Try the sample runbook' : 'Coba runbook contoh'}<ArrowRight size={16} aria-hidden="true" /></Link></div></div></div></article><section className="related-guides"><h2>{locale === 'en' ? 'Keep reading' : 'Panduan berikutnya'}</h2>{posts.filter(item => item.slug !== post.slug).map(item => <Link key={item.slug} href={`/blog/${item.slug}`}>{postTitle(item, locale)}<ArrowRight size={16} aria-hidden="true" /></Link>)}</section></main><MarketingFooter /></div>;
}
