import Link from 'next/link';
import { ArrowRight, Check, ChevronDown } from 'lucide-react';
import { useLanguage } from './language';
import { DocumentMascot } from './document-mascot';
import { readinessCopy } from '@/lib/readiness-copy';
import { knowledgeReadiness, type PreparedDocument, type Chunk } from '@/lib/documents';
export function ReadinessReport({document,chunks,trial=false,onNavigate}:{document:PreparedDocument;chunks:Chunk[];trial?:boolean;onNavigate?:(tab:string)=>void}) {
  const {locale}=useLanguage();const en=locale==='en';
  const report=knowledgeReadiness(document,chunks),copy=readinessCopy(locale);
  const status=copy.status[report.status as keyof typeof copy.status];
  return <section className={`readiness-report readiness-${report.status}`} aria-label="Knowledge Readiness Score"><div className="readiness-heading"><div className="readiness-score"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43"/><circle className="readiness-ring" cx="50" cy="50" r="43" pathLength="100" strokeDasharray={`${report.score} 100`}/></svg><strong>{report.score}<small>/100</small></strong></div><div className="readiness-summary"><span className="account-eyebrow">KNOWLEDGE READINESS</span><h3>{status}</h3><p>{report.status==='blocked'?(en?'Fix the missing title or empty sources before exporting.':'Perbaiki judul atau sumber kosong sebelum export.'):document.approved?(en?'Your review is recorded. The preparation package can be exported.':'Review kamu tercatat. Paket persiapan bisa diekspor.'):(en?'Check the extracted text against its source, then confirm your review.':'Cocokkan teks ekstraksi dengan sumber, lalu konfirmasi review.')}</p><div className="readiness-actions">{onNavigate&&<><button className="button outline" onClick={()=>onNavigate('source')}>{en?'Review source':'Periksa sumber'}<ArrowRight size={14}/></button><button className="button primary" onClick={()=>onNavigate('export')}>{document.approved?<Check size={15}/>:null}{en?'Review & export':'Review & export'}</button></>}</div></div><DocumentMascot state={report.status==='blocked'?'review':document.approved?'ready':'review'}/></div>
  <details className="readiness-details"><summary>{en?'Score breakdown & limitations':'Rincian skor & batasan'}<ChevronDown size={16}/></summary><div className="readiness-components">{report.components.map(component=><div key={component.id}><span>{copy.components[component.id as keyof typeof copy.components]} <small>({component.weight}%)</small></span><meter min={0} max={100} value={component.score} aria-label={copy.components[component.id as keyof typeof copy.components]}/><strong>{component.score}/100</strong></div>)}</div><p>{en?`${report.metrics.emptyUnits} empty sources · ${report.metrics.duplicateUnits} duplicate sections. Duplicates retain all references when merged.`:`${report.metrics.emptyUnits} sumber kosong · ${report.metrics.duplicateUnits} bagian duplikat. Penggabungan menjaga semua referensi.`}</p><p>{en?'A deterministic preparation checklist. The score does not predict AI answer quality.':'Checklist persiapan berbasis aturan. Skor tidak memprediksi kualitas jawaban AI.'}</p><small>{en?'Not assessed: ':'Belum dinilai: '}{Object.values(copy.unassessed).join(', ')}.</small>{trial&&<p>{en?'Metadata and chunk controls unlock after signup. You can review text and export Markdown in this trial.':'Pengaturan metadata dan chunk tersedia setelah daftar. Kamu bisa review teks dan export Markdown pada trial ini.'} <Link href="/register">{en?'Create an account':'Buat akun'}</Link></p>}</details></section>;
}
