import { useLanguage } from './language';
import { knowledgeReadiness, type PreparedDocument, type Chunk } from '@/lib/documents';

export function ReadinessReport({ document, chunks }: { document: PreparedDocument; chunks: Chunk[] }) {
  const { locale } = useLanguage();
  const en = locale === 'en';
  const report = knowledgeReadiness(document, chunks);
  const labels = en ? ['Extracted text coverage', 'Title, version and category', 'Distinct source text', 'Chunk source references', 'User review'] : ['Cakupan teks ekstraksi', 'Judul, versi, dan kategori', 'Keunikan teks sumber', 'Referensi sumber chunk', 'Review pengguna'];
  const statuses = en ? { blocked: 'Fix blockers first', 'needs-review': 'Review required', prepared: 'Prepared for handoff', 'needs-improvement': 'Complete preparation checks' } : { blocked: 'Perbaiki penghambat', 'needs-review': 'Perlu review', prepared: 'Siap diteruskan', 'needs-improvement': 'Lengkapi pemeriksaan persiapan' };
  return <section className="readiness-report" aria-label="Knowledge Readiness Score"><div className="readiness-heading"><div><h3>Knowledge Readiness Score</h3><p>{statuses[report.status as keyof typeof statuses]}</p></div><strong>{report.score}<small>/100</small></strong></div><p>{en ? 'A preparation checklist score calculated from your current document and chunks. It does not predict AI answer quality.' : 'Skor checklist persiapan dari dokumen dan chunk saat ini. Skor ini tidak memprediksi kualitas jawaban AI.'}</p><div className="readiness-components">{report.components.map((component, index) => <div key={component.id}><span>{labels[index]} <small>({component.weight}%)</small></span><meter min={0} max={100} value={component.score} aria-label={labels[index]}/><strong>{component.score}/100</strong></div>)}</div><p>{en ? `${report.metrics.emptyUnits} empty sources · ${report.metrics.duplicateUnits} duplicate sources. Fill metadata, inspect sources, configure deduplication and chunks, then approve in Export.` : `${report.metrics.emptyUnits} sumber kosong · ${report.metrics.duplicateUnits} sumber duplikat. Lengkapi metadata, periksa sumber, atur deduplikasi dan chunk, lalu setujui di Export.`}</p><small>{en ? 'Not assessed: semantics, retrieval accuracy, PII, language, OCR, and PDF table/layout fidelity. Duplicates are measured in source text even when merged in output.' : 'Belum dinilai: semantik, akurasi retrieval, PII, bahasa, OCR, dan ketepatan tabel/layout PDF. Duplikat dihitung pada teks sumber meski digabung pada hasil.'}</small></section>;
}
