import { pageTitles, type PageTitle } from './page-titles';
import type { Locale } from './i18n';

type Section = { id: string; heading: string; paragraphs: string[]; list?: string[]; example?: string };
type Copy = { excerpt: string; sections: Section[] };
export type BlogPost = { slug: string; pageTitle: PageTitle; category: 'extract' | 'chunk' | 'export'; published: string; en: Copy; id: Copy; sampleTab: string };
export const posts: BlogPost[] = [
  { slug: 'check-pdf-extraction', pageTitle: 'pdfguide', category: 'extract', published: '2026-10-08', sampleTab: 'source',
    en: { excerpt: 'A clean-looking page can hide mixed reading order or a detached table value. Here is what to check in the extracted text.', sections: [
      { id: 'select-text', heading: 'Start with text you can select', paragraphs: ['Open the original PDF and select a sentence. If the page is only an image, text extraction will need OCR first. A blank extraction can also come from a protected or unusually encoded file, so check the original before deciding it is a scan.', 'Precidoc currently extracts text from digital PDFs. OCR is not available in the workspace.'] },
      { id: 'reading-order', heading: 'Read a paragraph across the page boundary', paragraphs: ['Two columns, repeated headers and footnotes can change the order of extracted text. Compare the last lines of one page with the first lines of the next. A complete sentence is more useful than a high character count.'], list: ['Does the heading belong to the paragraph below it?', 'Did a second column get inserted halfway through a sentence?', 'Did a header or page number become part of an instruction?'] },
      { id: 'table-values', heading: 'Check the value and its label together', paragraphs: ['A value of 20% means little if its label disappears. In the sample recovery runbook, it refers to free disk space. Keep the parameter, value and unit together, then compare them with the original.', 'PDF table counts in Precidoc are unknown. A successful extraction does not prove that table rows or layout were preserved.'], example: 'Parameter: Free disk\nLimit: 20%\nSource: section_03 in the sample runbook' },
      { id: 'review-source', heading: 'Leave a path back to the source', paragraphs: ['Open Source & output and check the sections that matter to your workflow. Correct the extracted text if needed, keep its source references, and review the output again after an edit.', 'The readiness score flags preparation issues. It does not measure whether an AI answer will be correct. Treat the export as material you have reviewed, then evaluate it in the knowledge base where you plan to use it.'] },
    ] },
    id: { excerpt: 'Halaman yang terlihat rapi bisa menyimpan urutan baca yang tercampur atau nilai tabel tanpa label. Ini yang perlu diperiksa pada hasil teksnya.', sections: [
      { id: 'select-text', heading: 'Mulai dari teks yang bisa dipilih', paragraphs: ['Buka PDF asli lalu pilih satu kalimat. Jika halamannya hanya berupa gambar, ekstraksi teks memerlukan OCR terlebih dahulu. Hasil kosong juga bisa disebabkan file yang diproteksi atau encoding yang tidak biasa, jadi periksa sumbernya sebelum menyimpulkan bahwa file itu hasil scan.', 'Precidoc saat ini mengekstrak teks dari PDF digital. OCR belum tersedia di workspace.'] },
      { id: 'reading-order', heading: 'Baca paragraf yang melewati batas halaman', paragraphs: ['Dua kolom, header berulang, dan catatan kaki dapat mengubah urutan teks hasil ekstraksi. Bandingkan baris terakhir suatu halaman dengan baris awal halaman berikutnya. Kalimat yang utuh lebih berguna daripada jumlah karakter yang tinggi.'], list: ['Apakah judul sesuai dengan paragraf di bawahnya?', 'Apakah teks dari kolom kedua menyela sebuah kalimat?', 'Apakah header atau nomor halaman ikut masuk ke instruksi?'] },
      { id: 'table-values', heading: 'Periksa nilai bersama labelnya', paragraphs: ['Nilai 20% sulit dipahami jika labelnya hilang. Pada runbook pemulihan contoh, angka itu merujuk pada ruang disk kosong. Pertahankan parameter, nilai, dan satuannya, lalu bandingkan dengan dokumen asli.', 'Jumlah tabel pada PDF di Precidoc belum diketahui. Ekstraksi yang berhasil tidak membuktikan bahwa baris tabel atau layout tetap terjaga.'], example: 'Parameter: Ruang disk kosong\nBatas: 20%\nSumber: section_03 pada runbook contoh' },
      { id: 'review-source', heading: 'Pertahankan jalan kembali ke sumber', paragraphs: ['Buka Sumber & hasil lalu periksa bagian yang penting untuk alur kerjamu. Koreksi teks hasil ekstraksi jika diperlukan, pertahankan referensi sumber, dan tinjau kembali hasil setelah ada edit.', 'Skor kesiapan menandai masalah persiapan. Skor itu tidak mengukur apakah jawaban AI akan benar. Gunakan export sebagai materi yang sudah kamu periksa, lalu evaluasi pada knowledge base tempat kamu akan memakainya.'] },
    ] } },
  { slug: 'chunk-runbooks-with-context', pageTitle: 'chunkguide', category: 'chunk', published: '2026-10-08', sampleTab: 'chunks',
    en: { excerpt: 'A step without its prerequisite can become a different instruction. Review chunk boundaries before you use a runbook as context.', sections: [
      { id: 'complete-instruction', heading: 'Keep an instruction understandable on its own', paragraphs: ['A runbook often places a warning, a condition and a sequence of steps in the same section. If a chunk starts at step three, the reader may never see the condition that makes the action safe.', 'Read each chunk as if it were the only passage returned by your knowledge base. Can you tell what the action applies to, what must happen first and how to check the result?'] },
      { id: 'chunk-size', heading: 'Use size as a starting point', paragraphs: ['Precidoc splits source sections using a character limit and prefers available line or word boundaries. It does not identify semantic boundaries with an LLM.', 'Start with a size that fits an ordinary section. Review any section that becomes several chunks, especially a numbered procedure or a table. Adjust the size and inspect the new result; do not assume one setting will suit every document.'], list: ['Keep a condition close to the action it controls.', 'Check that a table still has its labels and units.', 'Look for warnings that became separated from their steps.'] },
      { id: 'duplicates', heading: 'Merge identical text with its references', paragraphs: ['Repeated passages can create several copies of the same instruction. Exact duplicate merging in Precidoc retains the source references on the remaining chunks.', 'Two passages with similar wording may still refer to different systems or versions. Exact matching does not detect those differences for you. Read the context before deciding that repetition is redundant.'] },
      { id: 'trace-back', heading: 'Check the route back to the runbook', paragraphs: ['A chunk should still point to the page or section it came from. Use that reference to verify the instruction and to locate the current version of its source.', 'After editing source text or changing chunk settings, review the result before exporting. The real test comes later: try representative questions in your retrieval system and inspect which passages it returns.'] },
    ] },
    id: { excerpt: 'Langkah tanpa prasyarat bisa menjadi instruksi yang berbeda. Periksa batas chunk sebelum menjadikan runbook sebagai konteks.', sections: [
      { id: 'complete-instruction', heading: 'Pastikan instruksi bisa dipahami sendiri', paragraphs: ['Runbook sering menempatkan peringatan, kondisi, dan urutan langkah dalam satu bagian. Jika chunk dimulai dari langkah ketiga, pembaca mungkin tidak melihat kondisi yang membuat tindakan itu aman.', 'Baca setiap chunk seolah-olah itu satu-satunya potongan yang dikembalikan knowledge base. Apakah kamu bisa memahami objek tindakan, hal yang harus dilakukan lebih dulu, dan cara memeriksa hasilnya?'] },
      { id: 'chunk-size', heading: 'Jadikan ukuran sebagai titik awal', paragraphs: ['Precidoc membagi bagian sumber dengan batas karakter dan mengutamakan batas baris atau kata yang tersedia. Precidoc belum mengenali batas makna dengan LLM.', 'Mulai dari ukuran yang sesuai dengan bagian biasa. Periksa bagian yang terpecah menjadi beberapa chunk, terutama prosedur bernomor atau tabel. Sesuaikan ukuran dan periksa hasil baru; satu pengaturan belum tentu sesuai untuk semua dokumen.'], list: ['Dekatkan kondisi dengan tindakan yang diaturnya.', 'Pastikan tabel tetap memiliki label dan satuan.', 'Cari peringatan yang terpisah dari langkah terkait.'] },
      { id: 'duplicates', heading: 'Gabungkan teks identik bersama referensinya', paragraphs: ['Bagian berulang bisa menghasilkan beberapa salinan instruksi yang sama. Penggabungan duplikat identik di Precidoc mempertahankan referensi sumber pada chunk yang tersisa.', 'Dua bagian dengan kata-kata mirip tetap bisa merujuk pada sistem atau versi yang berbeda. Pencocokan identik tidak mendeteksi perbedaan itu untukmu. Baca konteks sebelum menganggap suatu pengulangan tidak diperlukan.'] },
      { id: 'trace-back', heading: 'Periksa jalan kembali ke runbook', paragraphs: ['Chunk perlu tetap menunjuk halaman atau bagian asalnya. Gunakan referensi itu untuk memeriksa instruksi dan menemukan versi terbaru dari sumber.', 'Setelah mengedit teks sumber atau mengubah pengaturan chunk, tinjau hasil sebelum export. Pengujian sesungguhnya dilakukan setelahnya: coba pertanyaan yang mewakili kebutuhanmu pada sistem retrieval, lalu periksa potongan yang dikembalikan.'] },
    ] } },
  { slug: 'export-with-source-references', pageTitle: 'exportguide', category: 'export', published: '2026-10-08', sampleTab: 'export',
    en: { excerpt: 'An export needs more than clean text. Keep the version, review state and source references close enough to check later.', sections: [
      { id: 'metadata', heading: 'Name the document and its version', paragraphs: ['A file name may be useful to a person and unclear to an ingestion pipeline. Add a title, category and version when the source provides one.', 'Do not invent a version to fill a field. A missing version is useful information: it tells the next reviewer what still needs checking against the source.'] },
      { id: 'source-references', heading: 'Keep references beside the content', paragraphs: ['When a passage is edited or deduplicated, its source should remain traceable. Precidoc exports page or section references with chunks, including multiple references when identical chunks are merged.', 'The built-in Markdown sample uses section references. A digital PDF can use page references. Preserve whichever your document actually provides.'], example: 'Document → reviewed text → chunk\nChunk → source section or page\nMerged chunk → all retained source references' },
      { id: 'format', heading: 'Choose a format for the next step', paragraphs: ['JSON is useful when another tool will read structured document, chunk and preparation fields. Markdown is useful for a person reviewing the text and report.', 'Precidoc exports a preparation package, not a connection to your vector database. Check the destination schema and adapt the fields before ingestion. Both formats should retain the material you need for a later review.'] },
      { id: 'approval', heading: 'Review, then download', paragraphs: ['Check the source text, table values and metadata before approving the result. An edit or a change to chunk settings requires another review.', 'The current document session lives in browser memory. Download the export before refreshing or closing the tab. Keep it with the source document so the next person can reproduce your checks.'] },
    ] },
    id: { excerpt: 'Export membutuhkan lebih dari teks yang rapi. Simpan versi, status review, dan referensi sumber agar bisa diperiksa kembali.', sections: [
      { id: 'metadata', heading: 'Cantumkan judul dan versi dokumen', paragraphs: ['Nama file mungkin mudah dipahami manusia tetapi kurang jelas untuk alur ingestion. Tambahkan judul, kategori, dan versi jika sumber memang mencantumkannya.', 'Jangan mengarang versi untuk mengisi sebuah field. Versi yang kosong tetap memberi informasi: reviewer berikutnya tahu apa yang perlu dicocokkan dengan sumber.'] },
      { id: 'source-references', heading: 'Simpan referensi bersama konten', paragraphs: ['Saat sebuah bagian diedit atau digabungkan sebagai duplikat, sumbernya perlu tetap dapat ditelusuri. Precidoc mengekspor referensi halaman atau bagian bersama chunk, termasuk beberapa referensi saat chunk identik digabungkan.', 'Contoh Markdown bawaan memakai referensi bagian. PDF digital bisa memakai referensi halaman. Pertahankan jenis referensi yang memang dimiliki dokumenmu.'], example: 'Dokumen → teks yang ditinjau → chunk\nChunk → bagian atau halaman sumber\nChunk gabungan → semua referensi sumber yang dipertahankan' },
      { id: 'format', heading: 'Pilih format untuk langkah berikutnya', paragraphs: ['JSON berguna saat alat lain perlu membaca field dokumen, chunk, dan persiapan secara terstruktur. Markdown berguna saat seseorang akan membaca teks beserta laporannya.', 'Precidoc mengekspor paket persiapan, bukan koneksi ke vector database. Periksa schema tujuan dan sesuaikan field sebelum ingestion. Kedua format perlu mempertahankan materi yang diperlukan untuk review berikutnya.'] },
      { id: 'approval', heading: 'Review, lalu unduh', paragraphs: ['Periksa teks sumber, nilai tabel, dan metadata sebelum menyetujui hasil. Edit atau perubahan pengaturan chunk memerlukan review ulang.', 'Sesi dokumen saat ini berada di memori browser. Unduh export sebelum refresh atau menutup tab. Simpan bersama dokumen sumber agar orang berikutnya bisa mengulang pemeriksaanmu.'] },
    ] } },
];
export const getPost = (slug: string) => posts.find(post => post.slug === slug);
export const postTitle = (post: BlogPost, locale: Locale) => pageTitles[post.pageTitle][locale === 'en' ? 0 : 1];
export function readingMinutes(post: BlogPost, locale: Locale) {
  const copy = post[locale];
  const text = [postTitle(post, locale), copy.excerpt, ...copy.sections.flatMap(section => [section.heading, ...section.paragraphs, ...(section.list ?? []), section.example ?? ''])].join(' ');
  return Math.max(1, Math.ceil(text.split(/\s+/).length / 200));
}
